name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            rust: beta
            target: x86_64-unknown-linux-musl
            cross: false
          # - build: macos
          #   os: macos-latest
          #   rust: beta
          #   target: x86_64-apple-darwin
          #   cross: false
          # - build: windows
          #   os: windows-latest
          #   rust: beta
          #   target: x86_64-pc-windows-msvc
          #   cross: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            target: ${{ matrix.target }}
            override: true
            default: true
            components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Pagebrowse dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libgtk-4-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          libwebkit2gtk-4.1-dev
          gir1.2-javascriptcoregtk-4.1
          libjavascriptcoregtk-4.1-dev
          libsoup-3.0-dev
          webkit2gtk-driver
          at-spi2-core
          xvfb

      - name: Install pagebrowse manager
        run: cargo install pagebrowse_manager --root .

      - name: ls
        run: ls

      # TODO: install pagebrowse

      - name: Build Lib
        working-directory: ./toolproof
        run: cargo build

      - name: Test Lib
        working-directory: ./toolproof
         # toolproof tests itself when run
        run: xvfb-run cargo run -- --placeholders toolproof_path="$(pwd)/target/debug/toolproof"
